#!/usr/bin/env bash

set -eu

while true; do
    case "$PWD" in
        "$HOME"/*) ;;
        *)
            echo "Not within source directory." >&2
            exit 1
            ;;
    esac

    if [ -d .hg -o -d .git ]; then
        echo "$PWD"
        exit 0
    fi
    
    cd ..
done
