#!/usr/bin/env bash

set -eu


mk_add_options() {
    case "$1" in
        "MOZ_OBJDIR="*)
            echo "$1" | sed -e 's/^MOZ_OBJDIR=//'
            exit 0
            ;;
    esac
}

ac_add_options () {
    :
}

topsrcdir=$PWD
. mozconfig

if [ -x build/autoconf/config.guess ]; then
    echo "obj-$(build/autoconf/config.guess)"
    exit 0
fi

echo "Couldn't find MOZ_OBJDIR setting in $PWD/mozconfig" >&2
exit 1
